# version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: splitly-postgres
    env_file:
      - .env
    ports:
      - "5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db-init:/docker-entrypoint-initdb.d
    networks:
      - splitly-network

  backend:
    build: .
    container_name: splitly-backend
    ports:
      - "7005:8080"
    env_file:
      - .env
    depends_on:
      - postgres
    networks:
      - splitly-network

volumes:
  postgres_data:
  postgres_data_test:


networks:
  splitly-network:
