spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/splitly_db
    username: splitly
    password: password
    driver-class-name: org.postgresql.Driver
    servlet:
      multipart:
        max-file-size: 10MB
        max-request-size: 10MB

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  security:
    user:
      name: admin
      password: admin
  sql:
    init:
      mode: always
      continue-on-error: true

server:
  port: 8080
  servlet:
    context-path: /

gemini:
  api:
    key: ${GEMINI_API_KEY:AIzaSyCnu8qy7AJWpU6FkdEUV2ItKDYsjQX_gNc}
    url: https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent
