spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/splitly_db
    username: splitly
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  security:
    user:
      name: admin
      password: admin
  sql:
    init:
      mode: always
      continue-on-error: true

server:
  port: 8080
  servlet:
    context-path: /