name: Build a JAR in spring boot using springboot
on:
  push:
    branches:
      - develop

  pull_request:
    branches:
      - develop


jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Server
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: 160.191.50.208
          port: 6000
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /root/repo/Splitly-backend
            git pull origin develop
            
            # Build and Restart
            docker compose up -d --build
            docker ps
