name: Build a JAR in spring boot using springboot
on:
  push:
    branches:
      - develop

  pull_request:
    branches:
      - develop


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4


      - name: Set up JDK 21
        uses: actions/setup-java@v4


        with:
          java-version: '21'
          distribution: 'temurin'


      - name: Build without running tests
        run: mvn clean install -DskipTests # Option -DskipTests: Run without db in git workflow ci/cd, can use h2 to mock data latter

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-  
            
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4


        with:
          name: java-app
          path: '${{ github.workspace }}/target/*.jar'


#      - name: Run Tests
#        run: mvn test
